### ISSUE TITLE
Add support for different network names

### ISSUE THREAD

**Issue by ifavo** [vechainfoundation/hardhat-plugins#6]
Changing the network name to another one than `vechain` is not supported within the hardhat configuration.

Working example:

```shell
$ git clone https://github.com/vechainfoundation/hardhat-plugin-sample-ethers.git
$ yarn
$ npx hardhat run scripts/deploy.ts --network vechain
Compiled 1 Solidity file successfully
Storage deployed to 0xfFD4e670025092bECeD7562DdFfD4c78078CdC57
```

adjusting the configuration in `hardhat.config.ts` to call the network `testnet`:

```ts
    testnet: {
      url: "https://testnet.veblocks.net",
      accounts: {
        mnemonic: "denial kitchen pet squirrel other broom bar gas better priority spoil cross",
        count: 10,
      },
      restful: true,
      gas: 10000000
    }
```

will fail with `noNetwork`:

```shell
$ npx hardhat run scripts/deploy.ts --network testnet
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (./node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (./node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (./node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (./node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (./node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (./node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

expectation would be the same result as when it was named `vechain`.

**Comment by nwbrettski** [comment]
Hey @ifavo,

The latest release includes the ability to have a custom network name but the network name must include the word `vechain`. Examples of working custom network names include `vechain-testnet`, `vechain-main`, `vechainSolo` etc. Custom network names not including the word `vechain` will not function properly with Thor.

Latest release available here: https://www.npmjs.com/package/@vechain/hardhat-vechain
